apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tanzu-java-web-app-git2
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-git
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app-git2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/actuator: http://:8081/actuator
        boot.spring.io/version: 2.5.12
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          spring-boot-convention/spring-boot-actuator
          appliveview-sample/app-live-view-connector
          appliveview-sample/app-live-view-appflavours
          appliveview-sample/app-live-view-systemproperties
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"creationTimestamp":"2022-05-24T13:12:53Z","generation":1,"labels":{"app.kubernetes.io/part-of":"tanzu-java-web-app-git","apps.tanzu.vmware.com/workload-type":"web"},"name":"tanzu-java-web-app-git2","namespace":"default","resourceVersion":"7238128","uid":"d0b4ae78-b323-40cb-89a3-e43509a0c11e"},"spec":{"params":[{"name":"gitops_repository_prefix","value":"julien"},{"name":"gitops_repository","value":"ssh://git@github.com/J-kolaric/tanzu-java-web-app-deliverable.git"},{"name":"gitops_branch","value":"dev"},{"name":"gitops_user_name","value":"my_commit_user"},{"name":"gitops_user_email","value":"monusercommit@vmware.com"},{"name":"gitops_commit_message","value":"ready for push in dev branch"},{"name":"gitops_ssh_secret","value":"julien-ssh-secret"},{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/J-kolaric/tanzu-java-web-app"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-java-web-app-git
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: tanzu-java-web-app-git2
        conventions.apps.tanzu.vmware.com/framework: spring-boot
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.actuator.port: "8081"
        tanzu.app.live.view.application.flavours: spring-boot
        tanzu.app.live.view.application.name: demo
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.endpoint.health.show-details=always -Dmanagement.endpoints.web.base-path="/actuator" -Dmanagement.endpoints.web.exposure.include=* -Dmanagement.health.probes.enabled="true" -Dmanagement.server.port="8081" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: tapjko.azurecr.io/jkolaric/tap-workload/tanzu-java-web-app-git2-default@sha256:c1565178b40e5bc4a8f255762cefa48dbff8f412485e417a061958a551b6261c
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

